### ISSUE TITLE
sr25519

### ISSUE THREAD

**Issue by KimuraYu45z** [lcnem/cosmos-client-ts#10]
シュノア署名実装。

**Comment by KimuraYu45z** [comment]
rustでシュノア署名を実装しており、wasmを排出してそれをtsが利用する構造。

**Comment by KimuraYu45z** [comment]
本ライブラリでの完成済みのsecp256k1,ed25519の形式を参考に
https://github.com/lcnem/cosmos-client-ts/blob/master/src/tendermint/types/secp256k1.ts
https://github.com/lcnem/cosmos-client-ts/blob/master/src/tendermint/types/ed25519.ts

以下のファイルを完成させる。
https://github.com/lcnem/cosmos-client-ts/blob/master/src/tendermint/types/sr25519.ts

Rust WASMを呼び出す方法の参考
https://github.com/polkadot-js/wasm/blob/master/packages/wasm-crypto/src/js/index.js
https://github.com/polkadot-js/wasm/blob/master/packages/wasm-crypto/src/sr25519.rs

sr25519のtendermint上での仕様（公開鍵からアドレスを導出する方法の参考に）
https://github.com/tendermint/tendermint/tree/master/crypto/sr25519

**Comment by bcts369** [comment]
@KimuraYu45z 

動作確認の方法が浮かばないのですが、何か参考になる資料などありますでしょうか？

**Comment by KimuraYu45z** [comment]
https://github.com/lcnem/cosmos-client-ts/blob/master/src/tendermint/types/crypto.spec.ts

jestがインストールされてるのでこのファイルみたいにテストファイル書くだけで動作確認できます。
暗号なのでオフラインでいいですし副作用も必要ないので。

**Comment by KimuraYu45z** [comment]
cosmos-client-ts/src/tendermint/types/sr25519.spec.ts
をつくって、そこでテストコードを書いてください。

また、再確認ですが、イジる必要があるのは
https://github.com/lcnem/cosmos-client-ts/blob/master/src/tendermint/types/sr25519.ts
このファイルだけです。rustをwasmにコンパイルして吐き出してこのファイルがwasmを読むイメージです。

**Comment by bcts369** [comment]
了解しました。

**Comment by bcts369** [comment]
@KimuraYu45z 

木村さん的には、どのくらいの工数で完了すると思われますか？

**Comment by KimuraYu45z** [comment]
長くかかる場合の想定です
rustをwasmではかせるのに調査とか含めたら4h
sr25519.tsをいじるのに1h
テストに数h
くらいのもんだと思います

**Comment by bcts369** [comment]
うほー。
それほどの短い時間でできそうにないですが、善処します。

**Comment by bcts369** [comment]
結局やることが、わかっていればやれると思います。
手順を考えることから始めないといけないので、こういうのはどうかと？

**Comment by bcts369** [comment]
８Hくらいってことですよね。
厳しいと思ってますが、善処します。

**Comment by bcts369** [comment]
@KimuraYu45z 

wasm を生成するコマンドはどうしたらよいでしょうか？

**Comment by bcts369** [comment]
@KimuraYu45z 

`npm install` で警告が大量に表示されています。
お使いの node.js のバージョンを教えてください。

**Comment by KimuraYu45z** [comment]
@bcts369 添付したリンクを参考にしてそれを調べるのがタスクです

**Comment by bcts369** [comment]
@KimuraYu45z 

> 添付したリンクを参考にしてそれを調べるのがタスクです

そういうことですね。了解しました。

wasm-packというのを使うようです。

**Comment by bcts369** [comment]
> create-type = ["cdylib", "rlib"]

タスク外ではありますが、動的なライブラリの場合は、 `dylib` ではなかったでしょうか？

**Comment by KimuraYu45z** [comment]
@bcts369 
そのへんは
https://github.com/polkadot-js/wasm/blob/master/packages/wasm-crypto/src/js/index.js
これそのままもってきたのでよくわかりません。

やることとしては
https://github.com/lcnem/cosmos-client-ts/blob/master/src/tendermint/types/sr25519.ts
は俺が完成させたので（プルリクエストにあるやつ。このissueたてたときにはまだ完成してなかった）


https://github.com/lcnem/cosmos-client-ts/blob/master/src/tendermint/sr25519/src/index.js
にあるrequireにwasmを読ませればよいです


https://github.com/polkadot-js/schnorrkel-js/tree/master/src

このリポジトリを真似すればいけるはずです

**Comment by bcts369** [comment]
@KimuraYu45z 

了解しました。

**Comment by bcts369** [comment]
@KimuraYu45z 

現在以下の原因を調査中です。

```
➜  sr25519 git:(issue10) ✗ wasm-pack build
[INFO]: Checking for the Wasm target...
info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
 11.1 MiB /  11.1 MiB (100 %) 537.6 KiB/s in 22s ETA:  0s
info: installing component 'rust-std' for 'wasm32-unknown-unknown'
[INFO]: Compiling to Wasm...
   Compiling proc-macro2 v1.0.18
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.31
   Compiling log v0.4.8
   Compiling wasm-bindgen-shared v0.2.63
   Compiling cfg-if v0.1.10
   Compiling bumpalo v3.4.0
   Compiling lazy_static v1.4.0
   Compiling wasm-bindgen v0.2.63
   Compiling typenum v1.12.0
   Compiling getrandom v0.1.14
   Compiling byteorder v1.3.4
   Compiling byte-tools v0.3.1
   Compiling packed_simd v0.3.3
   Compiling ppv-lite86 v0.2.8
   Compiling fake-simd v0.1.2
   Compiling opaque-debug v0.2.3
   Compiling subtle v2.2.3
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/nao/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-2.2.3/src/lib.rs:12:34
   |
12 | #![cfg_attr(feature = "nightly", feature(external_doc))]
   |                                  ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `subtle`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
```

**Comment by bcts369** [comment]
@KimuraYu45z 

原因は、Cargo.tomlの設定にあるようです。引き続き調査します。

https://github.com/lcnem/cosmos-client-ts/blob/master/src/tendermint/sr25519/Cargo.toml#L15

**Comment by bcts369** [comment]
@KimuraYu45z 

とりあえずは、wasmのPKGが生成されました。内容が正しいのかどうかは現時点ではわかりません。

```
➜  sr25519 git:(issue10) ✗ wasm-pack build      
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling getrandom v0.1.14
   Compiling keccak v0.1.0
   Compiling subtle v2.2.3
   Compiling wee_alloc v0.4.5
   Compiling arrayvec v0.5.1
   Compiling arrayref v0.3.6
   Compiling memory_units v0.4.0
   Compiling proc-macro2 v1.0.18
   Compiling syn v1.0.31
   Compiling typenum v1.12.0
   Compiling byteorder v1.3.4
   Compiling wasm-bindgen-shared v0.2.63
   Compiling log v0.4.8
   Compiling block-padding v0.1.5
   Compiling wasm-bindgen v0.2.63
   Compiling rand_core v0.5.1
   Compiling quote v1.0.7
   Compiling rand_chacha v0.2.2
   Compiling generic-array v0.12.3
   Compiling rand v0.7.3
   Compiling digest v0.8.1
   Compiling block-buffer v0.7.3
   Compiling sha2 v0.8.2
   Compiling synstructure v0.12.4
   Compiling wasm-bindgen-backend v0.2.63
   Compiling wasm-bindgen-macro-support v0.2.63
   Compiling zeroize_derive v1.0.0
   Compiling wasm-bindgen-macro v0.2.63
   Compiling zeroize v1.1.0
   Compiling merlin v2.0.0
   Compiling curve25519-dalek v2.1.0
   Compiling schnorrkel v0.9.1
   Compiling crypto v0.1.0 (/home/nao/wip/cosmos-client-ts/src/tendermint/sr25519)
    Finished release [optimized] target(s) in 2m 49s
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 3m 44s
[INFO]: :-) Your wasm pkg is ready to publish at /home/nao/wip/cosmos-client-ts/src/tendermint/sr25519/pkg.
```

**Comment by bcts369** [comment]
@KimuraYu45z 

`cosmos-client-ts/src/tendermint/sr25519/pkg` 以下に次のようなファイルが生成されます。
これらを `.gitignore`  に含めるべきか判断がつかないのですが、どうしましょうか？

```
-rw-r--r-- 1 nao nao  102  6月 19 18:11 README.md
-rw-rw-r-- 1 nao nao 2.3K  6月 19 18:11 crypto.d.ts
-rw-rw-r-- 1 nao nao   73  6月 19 18:11 crypto.js
-rw-rw-r-- 1 nao nao  768  6月 19 18:11 crypto_bg.d.ts
-rw-rw-r-- 1 nao nao 5.4K  6月 19 18:11 crypto_bg.js
-rw-rw-r-- 1 nao nao 204K  6月 19 18:12 crypto_bg.wasm
-rw-rw-r-- 1 nao nao  277  6月 19 18:12 package.json
```

**Comment by bcts369** [comment]
自分用メモ

- [ ] wasm-pack buildのスコープに何を指定するべきかわからないので調査する。

**Comment by bcts369** [comment]
> @KimuraYu45z
> 
> `cosmos-client-ts/src/tendermint/sr25519/pkg` 以下に次のようなファイルが生成されます。
> これらを `.gitignore` に含めるべきか判断がつかないのですが、どうしましょうか？
> 
> ```
> -rw-r--r-- 1 nao nao  102  6月 19 18:11 README.md
> -rw-rw-r-- 1 nao nao 2.3K  6月 19 18:11 crypto.d.ts
> -rw-rw-r-- 1 nao nao   73  6月 19 18:11 crypto.js
> -rw-rw-r-- 1 nao nao  768  6月 19 18:11 crypto_bg.d.ts
> -rw-rw-r-- 1 nao nao 5.4K  6月 19 18:11 crypto_bg.js
> -rw-rw-r-- 1 nao nao 204K  6月 19 18:12 crypto_bg.wasm
> -rw-rw-r-- 1 nao nao  277  6月 19 18:12 package.json
> ```

npm パッケージに含める必要があるので、 `.gitignore` には含めない方がよさそうですね。

**Comment by bcts369** [comment]
@KimuraYu45z 

> $ wasm-pack build --scope `npm のユーザ名` 

でwasmを生成するのが正式っぽいですが、ユーザ名はどうしましょうか？

**Comment by KimuraYu45z** [comment]
ユーザー名はlcnemでお願いします。
gitignoreは含めるでお願いします。ビルド後のバイナリなので、ビルド方法を明記したうえで。

**Comment by bcts369** [comment]
> crate-type = ["cdylib", "rlib"]

が正しいです。 `dylib` ではありませんでした。エラーが発生します。

> Error: crate-type must be cdylib to compile to wasm32-unknown-unknown. Add the following to your Cargo.toml file:
[lib]
crate-type = ["cdylib", "rlib"]

**Comment by bcts369** [comment]
> ユーザー名はlcnemでお願いします。

試してみます。

> gitignoreは含めるでお願いします。ビルド後のバイナリなので、ビルド方法を明記したうえで。

トップのREADMEに追記（英語で）してもよいでしょうか？

**Comment by bcts369** [comment]
@KimuraYu45z 

スコープを指定して、wasmを生成してみました。

```
wasm-pack build --scope lcnem
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.40s
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 4.70s
[INFO]: :-) Your wasm pkg is ready to publish at /home/nao/wip/cosmos-client-ts/src/tendermint/sr25519/pkg.
```

**Comment by bcts369** [comment]
@KimuraYu45z 

今後の作業予定はこちらです。

https://github.com/lcnem/cosmos-client-ts/issues/10#issuecomment-646564303

本日はこれで終了するつもりです。

**Comment by KimuraYu45z** [comment]
wasm作成ありがとうございます。
readmeおーけーです。

**Comment by bcts369** [comment]
@KimuraYu45z 

明日は、次の内容を進めていきます。

他にやるべきことなど、ありましたら、ご指摘ください。

> 自分用メモ
> 
> * [x]  wasm-pack buildのスコープに何を指定するべきかわからないので調査する。
> * [ ]  info: installing component 'rust-std' for 'wasm32-unknown-unknown' というのが気持ち悪いので、確認する。
> * [ ]  wasmのパッケージをロードして、利用する方法を確認。
> * [ ]  --target オプションを調査する。

**Comment by bcts369** [comment]
@KimuraYu45z 

一通りの作業は終わりましたが、npm への更新は行っていません。

いったん、プルリクしても良いでしょうか？

**Comment by bcts369** [comment]
プルリクしました

**Comment by KimuraYu45z** [comment]
ありがとうございます！npmはやっときます。

**Comment by bcts369** [comment]
了解です。
