### ISSUE TITLE
Expected Private

### ISSUE THREAD

**Issue by AndrewVV** [lcnem/cosmos-client-ts#12]
I have a problem with PrivKeySecp256k1()

```
import { CosmosSDK, AccAddress, PrivKeySecp256k1 } from "cosmos-client";
const privKey = new PrivKeySecp256k1(new Buffer("my mneminic"));

ERROR: Expected Private
    at Object.pointFromScalar
    at new PrivKeySecp256k1

**Comment by KimuraYu45z** [comment]
Hello, thank you for using.

You shouldn't enter your mnemonic to 1st argument of Buffer constructor.
Needed is 32byte hex string.

If you want to generate a private key from a mnemonic, use bip39 library. It makes you able to get 32byte private key from mnemonic.

**Comment by KimuraYu45z** [comment]
I implemented it in this library just now.

Use:
`npm i --save cosmos-client@0.6.0`

Docs:

https://github.com/lcnem/cosmos-client-ts/blob/master/README.md

```ts
const privKeyBuffer = await sdk.generatePrivKeyFromMnemonic(mnemonic);
const privKey = new PrivKeySecp256k1(privKeyBuffer);
```

**Comment by AndrewVV** [comment]
Thank you!
This is exactly what I need
