### ISSUE TITLE
npm CD

### ISSUE THREAD

**Issue by KimuraYu45z** [lcnem/cosmos-client-ts#17]
【手持ち無沙汰なとき用タスク・優先順位低】

# やること1

githubでreleaseしたら自動でnpmにpublishさせたい。

# やること2

パッケージバージョンを、cosmos sdkのバージョンにあわせたい(0.38.x)
1桁目メジャーバージョンと2桁目マイナーバージョンは、sdkにあわせる。
3桁目fixバージョンは、独自にインクリメントしていっておｋ．

# やること3

1桁目メジャーバージョンと2桁目マイナーバージョンは、sdkにあわせる。
3桁目fixバージョンは、独自にインクリメントしていっておｋ．
というルールを、READMEのfor library developersに書く。

**Comment by KimuraYu45z** [comment]
github secret変数に`NPM_TOKEN`入れといたので、

GithubAction内で

```shell
echo "//registry.npmjs.org/:_authtoken=${NPM_TOKEN}" >> ~/.npmrc
```

**Comment by KimuraYu45z** [comment]
いえ、やること1はもう完了してます
https://github.com/lcnem/cosmos-client-ts/pull/18

**Comment by bcts369** [comment]
了解です。

**Comment by KimuraYu45z** [comment]
# やること4追加

npm run publishにしているbundle.jsだが、これなぜかnpm run publishが正常に完了してても最後throw errorで終わるのだけども、そちらの環境だとそうなりましたか？
なった場合、CDでも同様に、正常にpublishしてもエラー扱いになると思うので、解消する必要があります

**Comment by bcts369** [comment]
素のUbuuntuサーバーではそのような現象は起きてません。（18.04）
WSL上の20.04で確認します。

**Comment by bcts369** [comment]
package.jsonのバージョンを0.86に上げます。

**Comment by bcts369** [comment]
このようなエラーが発生しました

```
> cosmos-client@0.8.6 publish .
> node bundle && cd dist && npm publish

internal/modules/cjs/loader.js:969

  throw err;
  ^

Error: Cannot find module '/home/nao/wip/cosmos-client-ts/dist/bundle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by KimuraYu45z** [comment]
@bcts369 あ、実験用のバージョンですね。

そう、まさにそのエラーです。

**Comment by bcts369** [comment]
@KimuraYu45z 

> internal/modules/cjs/loader.js:969

見たことのないエラー箇所だな～。調べます。

**Comment by bcts369** [comment]
> # やること4追加
> npm run publishに使用しているbundle.jsだが、これなぜかnpm run publishが正常に完了してても最後throw errorで終わるのだけども、そちらの環境だとそうなりましたか？
> なった場合、CDでも同様に、正常にpublishしてもエラー扱いになると思うので、解消する必要があります

こちらの調査と実験をずっとしておりますが、現時点で解決できておりません。

いったん、やること２などの作業を行います。

**Comment by KimuraYu45z** [comment]
あー、実験のためにpublishするのであればバージョンはそのままのほうがよいです。
2はおいといて3お願いします。

**Comment by bcts369** [comment]
了解です。

**Comment by KimuraYu45z** [comment]
参考
https://teratail.com/questions/209749
https://teratail.com/questions/230116

**Comment by bcts369** [comment]
> あー、実験のためにpublishするのであればバージョンはそのままのほうがよいです。

`--dry-run`  オプションを使うと、実際のパブリッシュは行われないので、これを使うようにします。

**Comment by bcts369** [comment]
--dry-run オプションを付けて npm publish したのですが、普通にパプリッシュされてしまいました。すみません。

**Comment by KimuraYu45z** [comment]
あー原因がわかった
bundleでpackage.jsonをcopyしたあと、そのコピーしたpackage.jsonが再帰的に実行されるんんだわ

**Comment by KimuraYu45z** [comment]
2,3ができたらプルリクお願いします。

**Comment by bcts369** [comment]
@KimuraYu45z 
やること2ですが、Actionsの設定の調整を行えば良いのでしょうか？

**Comment by KimuraYu45z** [comment]
いえ、どう考えてもpackage.jsonのバージョンいじるだけです。。

**Comment by KimuraYu45z** [comment]
リリースのバージョンにあわせてpackage.jsonいじるなんて器用なこと、actionsでできるんですかね？

**Comment by KimuraYu45z** [comment]
ごめんなさい、あるみたいですね。

**Comment by KimuraYu45z** [comment]
いややっぱできませんでした
2も３ も秒速で終わります

**Comment by bcts369** [comment]
つまり、手動で 

package.json の `"version": "0.8.14"` となっている箇所を `0.38.1` などと書き換えれば良いということでしょうか？

**Comment by bcts369** [comment]
プルリク確認お願いします。

**Comment by KimuraYu45z** [comment]
書き換え、それ以外にありえません。ここは読解してほしいです。

**Comment by bcts369** [comment]
@KimuraYu45z 
自動で管理するものだと勘違いしました。申し訳ありませんでした。

**Comment by KimuraYu45z** [comment]
調べたらできないみたいだと言ったばかりです。

**Comment by bcts369** [comment]
失礼しました。
